version: '3'
services:
  db:
    build: enki-login-db
    hostname: enki-login-db
    ports:
      - "27017:27017"
    volumes:
      - "enki_db:/data/db"
      - "enki_configdb:/data/configdb"
  app:
    build: .
    hostname: enki-login-app
    ports:
      - "1337:1337"
    volumes:
      - "./config:/opt/enki/login/config:ro"
    depends_on:
      - db
    links:
      - db
volumes:
  enki_db:
  enki_configdb:
