/** Declaration file generated by dts-gen */

export = keccak;

declare function keccak(algorithm: string): any;
declare function keccak(algorithm: string, options: any): any;

declare namespace keccak {
    const prototype: {
    };
}
