/** Declaration file generated by dts-gen */

export function decode(input: Buffer): any;
export function decode(input: Buffer, stream: boolean): any;

export function encode(input: any): Buffer;

export function getLength(input: Buffer): number;

export namespace decode {
    const prototype: {
    };
}

export namespace encode {
    const prototype: {
    };
}

export namespace getLength {
    const prototype: {
    };
}
